### ISSUE TITLE
Allow telemetry config via environment variable

### ISSUE THREAD

**Issue by Eadword** [nomiclabs/hardhat#1283]
Currently playing around with hardhat + docker and I am running into an issue where it does not seem to fail due to not having the correct permissions to write the config file.

If I were building a docker image for this I could just inject the config file, but for right now my goal is to not need to build a new docker image every time I am trying to test it. I am just using docker as a guaranteed running environment.

This is the error I am seeing:
```
Creating uniswap-exporter_scraper_run ... done
/app # npx hardhat
An unexpected error occurred:

Error: EACCES: permission denied, mkdir '/root/.config/hardhat-nodejs'
    at Object.mkdirSync (node:fs:1014:3)
    at Object.mkdirsSync (/app/node_modules/hardhat/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at getConfigDirSync (/app/node_modules/hardhat/src/internal/util/global-dir.ts:27:6)
    at Object.hasConsentedTelemetry (/app/node_modules/hardhat/src/internal/util/global-dir.ts:109:21)
    at main (/app/node_modules/hardhat/src/internal/cli/cli.ts:120:49) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.config/hardhat-nodejs'
}
npm notice 
npm notice New minor version of npm available! 7.5.3 -> 7.6.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.0
npm notice Run npm install -g npm@7.6.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /app
npm ERR! command failed
npm ERR! command sh -c hardhat

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-27T05_33_11_991Z-debug.log
```

**Comment by alcuadrado** [comment]
Hey @Eadword, can you help us reproduce this? What's your Dockerfile? Thanks

**Comment by Eadword** [comment]
No dockerfile at this time @alcuadrado, this is primarlly so I can run it on my server without having to mess around with node envs. 

This is my docker-compose:
```yaml
version: '3.8'
services:
  scraper:
    container_name: app
    image: node:15-alpine
    volumes:
      - ./:/app
      - ~:/root   # this is what I did to make it work for now
    working_dir: /app
    entrypoint:
      - npx
    command:
      - hardhat
      - run
      - src/main.ts
```
