### ISSUE TITLE
Hardhat has trouble with Github Actions due to ethereumjs-abi

### ISSUE THREAD

**Issue by willKim19** [nomiclabs/hardhat#1717]
Running `npm ci` on Github actions fails because ethereumjs-abi pulls from github repositories rather than npm. Here's a snippet from the package-lock.json:

```json
            "eth-sig-util": {
              "version": "1.4.2",
              "resolved": "https://registry.npmjs.org/eth-sig-util/-/eth-sig-util-1.4.2.tgz",
              "integrity": "sha1-jZWCAsftuq6Dlwf7pvCf8ydgYhA=",
              "dev": true,
              "requires": {
                "ethereumjs-abi": "git+https://github.com/ethereumjs/ethereumjs-abi.git",
                "ethereumjs-util": "^5.1.1"
              }
            },
            "ethereumjs-abi": {
              "version": "git+https://github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0",
              "from": "git+https://github.com/ethereumjs/ethereumjs-abi.git",
              "dev": true,
              "requires": {
                "bn.js": "^4.11.8",
                "ethereumjs-util": "^6.0.0"
              },
```

This can be circumvented by forcing Github to use https instead of ssh in the Github Action, as such:

```yml
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Lint, test and compile
        run: |
          npm ci
```

Not sure if this is something you guys can fix, or if it's a downstream dependency, but wanted to share in case anyone runs into similar issues.
