### ISSUE TITLE
How to set alias for a library in hardhat.config.js ?

### ISSUE THREAD

**Issue by gzliudan** [nomiclabs/hardhat#1776]
Does hardhat support rename a library with specific version in hardhat.config.js? Like brownie can set remappings in brownie-config.yaml as below:
```yaml
compiler:
  solc:
    version: 0.5.17
    remappings:
      - "@openzeppelinV2=OpenZeppelin/openzeppelin-contracts@2.5.1"
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.1.0"
```

then use it in solidity file:
```solidity
import "@openzeppelinV2/contracts/token/ERC20/IERC20.sol";
```
